# Generated by Django 4.2 on 2024-10-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AgregadosC_B', '0001_initial'),
        ('System_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderpatient',
            fields=[
                ('idOrder', models.AutoField(primary_key=True, serialize=False)),
                ('codeOrder', models.CharField(max_length=10, unique=True, verbose_name='Codigo de pedido')),
                ('orderStatus', models.CharField(max_length=10, verbose_name='Estado del pedido')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('dateOrder', models.DateField(verbose_name='Fecha de creacion del pedido')),
                ('adminFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='System_Admin.systemadmin', verbose_name='Encargado del sistema')),
                ('aggregatesFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AgregadosC_B.aggregates_cb', verbose_name='Agregados')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
