# Generated by Django 4.2 on 2024-10-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Condicion', '0002_alter_condition_lvl_options'),
        ('Paciente', '0001_initial'),
        ('DetallesEnfermedad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expedientPatient',
            fields=[
                ('idExpedient', models.AutoField(primary_key=True, serialize=False)),
                ('codeExpedient', models.CharField(max_length=10, unique=True, verbose_name='Código del Expediente')),
                ('reasonConsult', models.CharField(max_length=80, verbose_name='Motivo de consulta')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='Diagnóstico')),
                ('treatment', models.CharField(max_length=60, verbose_name='Tratamiento')),
                ('dietaryRestrictions', models.CharField(max_length=200, verbose_name='Restricciones alimenticias')),
                ('dietaryPreferences', models.CharField(max_length=100, verbose_name='Preferencias alimenticias')),
                ('attedingPhysician', models.CharField(max_length=20, verbose_name='Médico a cargo')),
                ('conditionFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Condicion.condition_lvl', verbose_name='Condición')),
                ('detailDiseaseFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DetallesEnfermedad.detaildisease', verbose_name='Detalles de la enfermedad')),
                ('patientFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paciente.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name_plural': 'Expedientes de Pacientes',
            },
        ),
    ]
