# Generated by Django 4.2 on 2024-10-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('idFood', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('foodName', models.CharField(max_length=60, verbose_name='Nombre de comida')),
                ('foodDescription', models.CharField(max_length=110, verbose_name='Descripción de la comida')),
                ('foodType', models.CharField(max_length=50, verbose_name='Tipo de comida')),
                ('Ingredients_food', models.CharField(max_length=120, verbose_name='Ingredientes de la comida')),
            ],
            options={
                'verbose_name_plural': 'Comidas',
            },
        ),
    ]
