# Generated by Django 4.2 on 2024-10-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comidas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='foodType',
        ),
    ]
