# Generated by Django 4.2 on 2025-06-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIM_SYSTEM_ADMIN_DEST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAdmin', models.IntegerField()),
                ('namesAdmin', models.CharField(max_length=60)),
                ('lastNameAdmin', models.CharField(max_length=60)),
                ('phoneAdmin', models.CharField(max_length=15)),
                ('Username', models.CharField(max_length=80)),
            ],
            options={
                'db_table': '[dbo].[DIM_SYSTEM_ADMIN_DEST]',
                'managed': False,
            },
        ),
    ]
