# Generated by Django 4.2 on 2024-10-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PedidoPaciente', '0001_initial'),
        ('Camas', '0001_initial'),
        ('ExpedientePaciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_History',
            fields=[
                ('idMedicalHistory', models.AutoField(primary_key=True, serialize=False)),
                ('codeHistory', models.CharField(max_length=10, unique=True, verbose_name='Código de historial')),
                ('dateHistory', models.DateField(auto_now=True, verbose_name='Fecha del historial')),
                ('bedFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Camas.beds', verbose_name='Cama del paciente')),
                ('expedientP_FK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ExpedientePaciente.expedientpatient', verbose_name='Expediente del paciente')),
                ('orderFk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PedidoPaciente.orderpatient', verbose_name='Pedido del Paciente')),
            ],
            options={
                'verbose_name_plural': 'Historiales Médicos',
            },
        ),
    ]
