# Generated by Django 4.2 on 2024-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial_Medico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='active_Patient',
            field=models.BooleanField(default=True),
        ),
    ]
