# Generated by Django 4.2 on 2024-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Camas', '0001_initial'),
        ('Historial_Medico', '0003_alter_medical_history_orderfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='bedFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_medicos', to='Camas.beds', verbose_name='Cama del paciente'),
        ),
    ]
