# Generated by Django 4.2 on 2025-06-08 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoPaciente', '0001_initial'),
        ('Historial_Medico', '0004_alter_medical_history_bedfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='orderFk',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='PedidoPaciente.orderpatient', verbose_name='Pedido del Paciente'),
        ),
    ]
