# Generated by Django 4.2 on 2024-10-01 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TiposEnfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diseases',
            fields=[
                ('idDisease', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nameDisease', models.CharField(max_length=50, verbose_name='Nombre de la enfermedad')),
                ('typeDiseaseFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TiposEnfermedades.typedisease', verbose_name='Tipo de enfermedad')),
            ],
            options={
                'verbose_name_plural': 'Listado de Enfermedades',
            },
        ),
    ]
