# Generated by Django 4.2 on 2024-10-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beverages',
            fields=[
                ('idBeverages', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NameBeverage', models.CharField(max_length=60, verbose_name='Nombre de la bebida')),
                ('Beverage_description', models.CharField(max_length=110, verbose_name='Descripción de la bebida')),
                ('TypeBeverage', models.CharField(max_length=50, verbose_name='Tipo de la bebida')),
                ('Ingredients_Beverage', models.CharField(max_length=120, verbose_name='Ingredientes de la bebida')),
            ],
            options={
                'verbose_name_plural': 'Bebidas',
            },
        ),
    ]
