# Generated by Django 4.2 on 2024-10-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Paciente', '0001_initial'),
        ('Enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailDisease',
            fields=[
                ('idDetailDisease', models.AutoField(primary_key=True, serialize=False)),
                ('diseaseFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Enfermedades.diseases', verbose_name='Enfermedad')),
                ('patient_dFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Paciente.patient', verbose_name='Paciente')),
            ],
            options={
                'verbose_name_plural': 'Detalles de enfermedad del paciente',
            },
        ),
    ]
