# Generated by Django 4.2 on 2025-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpedientePaciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientpatient',
            name='attedingPhysician',
            field=models.CharField(max_length=85, verbose_name='Médico a cargo'),
        ),
        migrations.AlterField(
            model_name='expedientpatient',
            name='codeExpedient',
            field=models.CharField(max_length=60, unique=True, verbose_name='Código del Expediente'),
        ),
    ]
