# Generated by Django 4.2 on 2024-10-01 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UnidadesCuidados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='beds',
            fields=[
                ('idbed', models.AutoField(primary_key=True, serialize=False)),
                ('bedCode', models.CharField(max_length=10, unique=True, verbose_name='Código de cama')),
                ('CareUnitFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='UnidadesCuidados.careunit', verbose_name='Unidad de cuidado')),
            ],
            options={
                'verbose_name_plural': 'Camas',
            },
        ),
    ]
