# Generated by Django 4.2 on 2025-06-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIM_TIEMPO_DEST',
            fields=[
                ('TiempoKey', models.IntegerField(primary_key=True, serialize=False)),
                ('FechaCompleta', models.DateField()),
                ('Anio', models.IntegerField()),
                ('MesNumero', models.IntegerField()),
                ('NombreMes', models.CharField(max_length=30)),
                ('DiaDelMes', models.IntegerField()),
                ('DiaSemanaNumero', models.IntegerField()),
                ('NombreDiaSemana', models.CharField(max_length=30)),
                ('TrimestreNumero', models.IntegerField()),
                ('NombreTrimestre', models.CharField(max_length=62)),
                ('SemanaDelAnioNumero', models.IntegerField()),
                ('EsFinDeSemana', models.CharField(max_length=30)),
                ('NombreEsFinDeSemana', models.CharField(max_length=2)),
            ],
            options={
                'db_table': '[dbo].[DIM_TIEMPO_DEST]',
                'managed': False,
            },
        ),
    ]
