# Generated by Django 4.2 on 2024-10-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TiposComida', '0001_initial'),
        ('Comidas', '0002_remove_foods_foodtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='typeFoodFK',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TiposComida.typefood', verbose_name='Tipo de comida'),
        ),
    ]
