# Generated by Django 4.2 on 2024-10-02 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bebidas', '0001_initial'),
        ('Comidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aggregates_cb',
            fields=[
                ('idAggregates', models.AutoField(primary_key=True, serialize=False)),
                ('codeAggregates', models.CharField(max_length=10, unique=True, verbose_name='Código de agregados')),
                ('beverageFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Bebidas.beverages', verbose_name='Bebida agregada')),
                ('foodFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Comidas.foods', verbose_name='Comida agregada')),
            ],
            options={
                'verbose_name_plural': 'Agregados',
            },
        ),
    ]
