# Generated by Django 4.2 on 2025-06-11 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bebidas', '0004_alter_beverages_typebeveragesfk'),
        ('Comidas', '0003_foods_typefoodfk'),
        ('AgregadosC_B', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregates_cb',
            name='beverageFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Bebidas.beverages', verbose_name='Bebida agregada'),
        ),
        migrations.AlterField(
            model_name='aggregates_cb',
            name='foodFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Comidas.foods', verbose_name='Comida agregada'),
        ),
    ]
