# Generated by Django 4.2 on 2025-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnidadesCuidados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careunit',
            name='nameCareUnit',
            field=models.CharField(max_length=250, verbose_name='Nombre de unidad de cuidado'),
        ),
    ]
