# Generated by Django 4.2 on 2024-10-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typeBeverage',
            fields=[
                ('id_typeBeverage', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description_TypeBeverage', models.CharField(max_length=80, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de bebida',
            },
        ),
    ]
