# Generated by Django 4.2 on 2024-10-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Condicion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition_lvl',
            options={'verbose_name_plural': 'Condiciones'},
        ),
    ]
