# Generated by Django 4.2 on 2024-10-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typedisease',
            fields=[
                ('idtype', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nametype', models.CharField(max_length=60, verbose_name='Nombre del tipo de enfermedad')),
            ],
            options={
                'verbose_name_plural': 'Tipos de enfermedad',
            },
        ),
    ]
