# Generated by Django 4.2 on 2025-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beds',
            name='bedCode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código de cama'),
        ),
    ]
