# Generated by Django 4.2 on 2024-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemadmin',
            name='password',
        ),
        migrations.AddField(
            model_name='systemadmin',
            name='Password_admin',
            field=models.CharField(default=None, max_length=15, verbose_name='<PASSWORD>'),
        ),
    ]
