# Generated by Django 4.2 on 2025-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Admin', '0002_remove_systemadmin_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemadmin',
            name='Username',
            field=models.CharField(max_length=80, verbose_name='Nombre de Usuario'),
        ),
    ]
