# Generated by Django 4.2 on 2024-10-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('idpatient', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('namesPatient', models.CharField(max_length=60, verbose_name='Nombres del paciente')),
                ('lastnamePatient', models.CharField(max_length=60, verbose_name='Apellidos del paciente')),
                ('cedulaPatient', models.CharField(max_length=14, verbose_name='Cédula del paciente')),
                ('genderPatient', models.CharField(max_length=10, verbose_name='Sexo del paciente')),
                ('agePatient', models.IntegerField(verbose_name='Age del paciente')),
                ('phonePatient', models.CharField(max_length=15, verbose_name='Teléfono del paciente')),
            ],
            options={
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
