# Generated by Django 4.2 on 2025-06-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIM_HISTORIAL_MEDICO_DEST',
            fields=[
                ('idMedicalHistory', models.IntegerField(primary_key=True, serialize=False)),
                ('dateHistory', models.DateField()),
                ('codeHistory', models.CharField(max_length=60)),
                ('bedCode', models.CharField(max_length=100, unique=True)),
                ('NameCareUnit', models.CharField(max_length=250)),
                ('CodeExpedient', models.CharField(max_length=60)),
                ('ReasonConsult', models.CharField(max_length=80)),
                ('Diagnosis_Evento', models.CharField(max_length=50)),
                ('Treatment_Evento', models.CharField(max_length=60)),
                ('dietaryRestrictions', models.CharField(max_length=200)),
                ('dietaryPreferences', models.CharField(max_length=100)),
                ('attedingPhysician', models.CharField(max_length=85)),
                ('ConditionName', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '[dbo].[DIM_HISTORIAL_MEDICO_DEST]',
                'managed': False,
            },
        ),
    ]
