# Generated by Django 4.2 on 2025-06-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DIM_PACIENTE_DEST',
            fields=[
                ('PatientKey', models.IntegerField(primary_key=True, serialize=False)),
                ('namesPatient', models.CharField(max_length=60)),
                ('lastnamePatient', models.CharField(max_length=60)),
                ('agePatient', models.IntegerField()),
                ('cedulaPatient', models.CharField(max_length=14)),
                ('phonePatient', models.CharField(max_length=15)),
                ('genderPatient', models.CharField(max_length=10)),
            ],
            options={
                'db_table': '[dbo].[DIM_PACIENTE_DEST]',
                'managed': False,
            },
        ),
    ]
