# Generated by Django 4.2 on 2025-05-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historial_Medico', '0004_alter_medical_history_bedfk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_history',
            name='codeHistory',
            field=models.CharField(max_length=60, unique=True, verbose_name='Código de historial'),
        ),
    ]
