# Generated by Django 4.2 on 2024-10-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='typefood',
            fields=[
                ('idTypeFood', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description_typefood', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de comida',
            },
        ),
    ]
